package com.exampleSpringBoot.springBootFirstApiRest.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Objects;

@Entity
@Table(name = "TODO")
@Getter
@Setter
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "id",
        "name",
        "assignee",
        "due",
        "notes",
        "activeFlag"
})
public class Todo {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonPropertyDescription("The unique identifier, generated by TodoService on addition")
    private Long id;

    @Column(name = "NAME", nullable = false)
    private String name;

    @Column(name = "ASSIGNEE", length = 50)
    @JsonProperty(required = true)
    @JsonPropertyDescription("The unique name of the Todo")
    private String assignee;

    @JsonPropertyDescription("A due date of the Todo")
    @Column(name = "DUE")
    private String due;

    @JsonPropertyDescription("Any notes associated with the Todo")
    @Column(name = "NOTES", length = 250)
    private String notes;


    @JsonProperty(defaultValue = "true")
    @JsonPropertyDescription("Active flag determining the status of the Todo")
    @Column(name = "ACTIVE", nullable = false)
    private Boolean activeFlag;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Todo todo = (Todo) o;
        return Objects.equals(id, todo.id) && Objects.equals(name, todo.name) && Objects.equals(assignee, todo.assignee) && Objects.equals(due, todo.due) && Objects.equals(notes, todo.notes) && Objects.equals(activeFlag, todo.activeFlag);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, assignee, due, notes, activeFlag);
    }
}
